"""
transcript_quality.py

Deterministic, rule-based transcript quality analyser.

No external dependencies, no network calls.  All logic is heuristic and
intentionally kept simple so thresholds are easy to read and change.
"""
from __future__ import annotations

import re
import unicodedata

# ---------------------------------------------------------------------------
# Public types
# ---------------------------------------------------------------------------

TranscriptQualityLevel = str  # "high" | "medium" | "low"

# ---------------------------------------------------------------------------
# Thresholds — adjust here if heuristics need tuning
# ---------------------------------------------------------------------------

_MIN_CHARS_FOR_QUALITY = 50           # below this → low quality regardless
_REPLACEMENT_CHAR = "\ufffd"           # Unicode replacement character "�"
_MAX_REPLACEMENT_RATIO = 0.01         # >1 % → quality degrades
_HIGH_UNUSUAL_RATIO = 0.15            # >15 % unusual chars → low
_MEDIUM_UNUSUAL_RATIO = 0.07          # >7 % → medium
_LOW_THAI_RATIO_THRESHOLD = 0.05      # Thai text with <5 % Thai chars → suspicious
_HIGH_LATIN_IN_THAI_THRESHOLD = 0.35  # >35 % Latin in a Thai transcript → suspicious
_REPEATED_PHRASE_MIN_LENGTH = 12      # minimum length of phrase to consider repetition
_REPEATED_PHRASE_MIN_REPEATS = 4      # must repeat at least N times to flag


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def analyze_transcript_quality(
    transcript: str,
    transcript_source: str | None = None,
    language: str = "thai",
) -> dict:
    """
    Analyse *transcript* and return a quality dict.

    Return shape::

        {
            "transcript_quality": "high" | "medium" | "low",
            "warnings": [...],
            "quality_signals": {
                "char_count": int,
                "unusual_character_ratio": float,
                "latin_character_ratio": float,
                "thai_character_ratio": float,
                "replacement_character_count": int,
                "repeated_phrase_detected": bool,
            },
        }
    """
    warnings: list[str] = []

    # --- Static STT warning -----------------------------------------------
    if transcript_source == "local_stt":
        warnings.append(
            "Transcript generated by local STT. "
            "Some words, names, or technical terms may be inaccurate."
        )

    # --- Early exit on empty / very short transcript ----------------------
    text = transcript.strip()
    if not text or len(text) < _MIN_CHARS_FOR_QUALITY:
        warnings.append("Transcript is too short to assess quality reliably.")
        return _build_result("low", warnings, text)

    # --- Compute signals ---------------------------------------------------
    char_count = len(text)
    replacement_count = text.count(_REPLACEMENT_CHAR)

    thai_chars = sum(1 for ch in text if "\u0e00" <= ch <= "\u0e7f")
    latin_chars = sum(1 for ch in text if "A" <= ch <= "Z" or "a" <= ch <= "z")
    unusual_chars = sum(1 for ch in text if _is_unusual(ch))

    thai_ratio = thai_chars / char_count
    latin_ratio = latin_chars / char_count
    unusual_ratio = unusual_chars / char_count
    replacement_ratio = replacement_count / char_count

    repeated = _has_repeated_phrase(text)

    signals = {
        "char_count": char_count,
        "unusual_character_ratio": round(unusual_ratio, 4),
        "latin_character_ratio": round(latin_ratio, 4),
        "thai_character_ratio": round(thai_ratio, 4),
        "replacement_character_count": replacement_count,
        "repeated_phrase_detected": repeated,
    }

    # --- Warnings from signals -------------------------------------------
    if replacement_count > 0:
        warnings.append(
            f"Transcript contains {replacement_count} replacement character(s) '\\ufffd' "
            "which may indicate encoding issues or failed character recognition."
        )

    if repeated:
        warnings.append(
            "Repeated phrase pattern detected. "
            "The transcript may contain looped or garbled output from the STT model."
        )

    lang_lower = (language or "").lower().strip()

    if lang_lower == "thai":
        if thai_ratio < _LOW_THAI_RATIO_THRESHOLD and char_count > 100:
            warnings.append(
                "Very few Thai characters found in a Thai-language transcript. "
                "The STT may have transcribed in the wrong language."
            )
        if latin_ratio > _HIGH_LATIN_IN_THAI_THRESHOLD:
            warnings.append(
                f"High proportion of Latin characters ({latin_ratio:.0%}) in a Thai transcript. "
                "Product names, technical terms, or mixed-language content may be inaccurate."
            )

    # --- Determine quality level -----------------------------------------
    quality: TranscriptQualityLevel
    if (
        unusual_ratio >= _HIGH_UNUSUAL_RATIO
        or replacement_ratio > _MAX_REPLACEMENT_RATIO
        or repeated
        or (lang_lower == "thai" and thai_ratio < _LOW_THAI_RATIO_THRESHOLD and char_count > 100)
    ):
        quality = "low"
    elif unusual_ratio >= _MEDIUM_UNUSUAL_RATIO or (
        lang_lower == "thai" and latin_ratio > _HIGH_LATIN_IN_THAI_THRESHOLD
    ):
        quality = "medium"
    else:
        quality = "high"

    # STT source alone never upgrades quality beyond medium if we already
    # have a non-high rating; but a clean STT transcript can still be high.
    # (No extra downgrade here — the signal checks above cover it.)

    return _build_result(quality, warnings, text, signals)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _build_result(
    quality: TranscriptQualityLevel,
    warnings: list[str],
    text: str,
    signals: dict | None = None,
) -> dict:
    if signals is None:
        char_count = len(text)
        signals = {
            "char_count": char_count,
            "unusual_character_ratio": 0.0,
            "latin_character_ratio": 0.0,
            "thai_character_ratio": 0.0,
            "replacement_character_count": 0,
            "repeated_phrase_detected": False,
        }
    return {
        "transcript_quality": quality,
        "warnings": warnings,
        "quality_signals": signals,
    }


def _is_unusual(ch: str) -> bool:
    """Return True for characters that are suspicious in a Thai/English transcript."""
    # Allow: Thai, Latin (A-Z a-z 0-9), common punctuation & whitespace.
    if "\u0e00" <= ch <= "\u0e7f":   # Thai block
        return False
    if ch.isalnum() or ch in " \t\n\r.,!?;:\"'()-–—…_/\\@#%&*+=<>[]{}|~`^":
        return False
    # Replacement char counts separately
    if ch == _REPLACEMENT_CHAR:
        return True
    # Other non-ASCII that isn't Thai — flag as unusual
    try:
        cat = unicodedata.category(ch)
    except Exception:
        return True
    # Allow Zs (space separators), Pd (dashes), Po (other punctuation)
    if cat in {"Zs", "Pd", "Po", "Pi", "Pf"}:
        return False
    # Mn, Mc: combining marks (often used in Thai vowels) — allow
    if cat in {"Mn", "Mc"}:
        return False
    if ord(ch) < 128:
        return False
    return True


def _has_repeated_phrase(text: str, min_len: int = _REPEATED_PHRASE_MIN_LENGTH, min_repeats: int = _REPEATED_PHRASE_MIN_REPEATS) -> bool:
    """
    Return True when a contiguous phrase of at least *min_len* characters
    appears at least *min_repeats* times in a row or overall.
    """
    # Look for any n-gram of word tokens repeated consecutively.
    words = text.split()
    if len(words) < min_repeats * 2:
        return False

    # Check for any window of 3 consecutive words repeated min_repeats times.
    window = 3
    if len(words) < window:
        return False

    for start in range(len(words) - window * min_repeats + 1):
        phrase = " ".join(words[start : start + window])
        if len(phrase) < min_len:
            continue
        # Count total occurrences in the full text
        count = 0
        pos = 0
        escaped = re.escape(phrase)
        for _match in re.finditer(escaped, text):
            count += 1
        if count >= min_repeats:
            return True
    return False
